/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/evm/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token Transfers
         * @description Returns ERC-20 and native token transfers with transaction and block data.
         */
        get: operations["getEvmTransfers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/swaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Swap Events
         * @description Returns DEX swap transactions from Uniswap protocols with token amounts and prices.
         */
        get: operations["getEvmSwaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token Metadata
         * @description Returns ERC-20 token metadata including symbol, name, decimals, supply, and holder information.
         */
        get: operations["getEvmTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token Balances
         * @description Returns current token holdings for any wallet address.
         */
        get: operations["getEvmBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/holders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token Holders
         * @description Returns the list of holders for a specific token.
         */
        get: operations["getEvmHolders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Token Prices
         * @description Returns current USD prices for tokens.
         */
        get: operations["getEvmPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/ohlc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OHLC Price Data
         * @description Returns OHLCV candlestick data for token prices.
         */
        get: operations["getEvmOhlc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evm/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liquidity Pools
         * @description Returns DEX liquidity pool information including token pairs and trading fees.
         */
        get: operations["getEvmPools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns the health status of the API.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Version
         * @description Returns the current API version.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supported Networks
         * @description Returns the list of supported blockchain networks.
         */
        get: operations["getNetworks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UsageInfo: {
            balance_remaining?: number;
            total_count?: number;
            elapsed_time_ms?: number;
        };
        PaginationInfo: {
            page?: number;
            limit?: number;
            total_pages?: number;
        };
        Transfer: {
            /** @description Block number */
            block_num: number;
            /** @description Human-readable datetime */
            datetime: string;
            /** @description Unix timestamp */
            timestamp: number;
            /** @description Transaction hash */
            transaction_id: string;
            /** @description Token contract address */
            contract: string;
            /** @description Sender address */
            from: string;
            /** @description Recipient address */
            to: string;
            /** @description Token name */
            name?: string | null;
            /** @description Token symbol */
            symbol?: string | null;
            /** @description Token decimals */
            decimals?: number | null;
            /** @description Raw transfer amount */
            amount: string;
            /** @description Human-readable transfer value */
            value: number;
            /** @description Network ID */
            network: string;
        };
        TransfersResponse: {
            data?: components["schemas"]["Transfer"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        TokenInfo: {
            address: string;
            symbol: string;
            decimals: number;
        };
        Swap: {
            /** @description Block number */
            block_num: number;
            /** @description Human-readable datetime */
            datetime: string;
            /** @description Unix timestamp */
            timestamp: number;
            /** @description Transaction hash */
            transaction_id: string;
            /** @description Factory contract address */
            factory?: string;
            /** @description Pool contract address */
            pool: string;
            input_token: components["schemas"]["TokenInfo"];
            output_token: components["schemas"]["TokenInfo"];
            /** @description Caller address */
            caller: string;
            /** @description Sender address */
            sender: string;
            /** @description Recipient address */
            recipient: string;
            /** @description Raw input amount */
            input_amount: string;
            /** @description Human-readable input value */
            input_value: number;
            /** @description Raw output amount */
            output_amount: string;
            /** @description Human-readable output value */
            output_value: number;
            /** @description Price ratio */
            price: number;
            /** @description Inverse price ratio */
            price_inv?: number;
            /** @description DEX protocol (uniswap_v2, uniswap_v3) */
            protocol: string;
            /** @description Human-readable swap summary */
            summary?: string;
            /** @description Network ID */
            network: string;
        };
        SwapsResponse: {
            data?: components["schemas"]["Swap"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        Token: {
            contract: string;
            name: string;
            symbol: string;
            decimals: number;
            total_supply?: string;
            holders_count?: number;
            network: string;
        };
        TokensResponse: {
            data?: components["schemas"]["Token"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        Balance: {
            owner: string;
            contract: string;
            name?: string | null;
            symbol?: string | null;
            decimals?: number | null;
            amount: string;
            value: number;
            network: string;
        };
        BalancesResponse: {
            data?: components["schemas"]["Balance"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        Holder: {
            owner: string;
            contract: string;
            amount: string;
            value: number;
            network: string;
        };
        HoldersResponse: {
            data?: components["schemas"]["Holder"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        Price: {
            contract: string;
            symbol?: string | null;
            name?: string | null;
            price_usd: number;
            network: string;
        };
        PricesResponse: {
            data?: components["schemas"]["Price"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        Ohlc: {
            datetime: string;
            timestamp: number;
            open: number;
            high: number;
            low: number;
            close: number;
            volume: number;
        };
        OhlcResponse: {
            data?: components["schemas"]["Ohlc"][];
            usage?: components["schemas"]["UsageInfo"];
        };
        Pool: {
            pool: string;
            factory: string;
            token0: components["schemas"]["TokenInfo"];
            token1: components["schemas"]["TokenInfo"];
            fee: number;
            protocol: string;
            network: string;
        };
        PoolsResponse: {
            data?: components["schemas"]["Pool"][];
            usage?: components["schemas"]["UsageInfo"];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
        };
        VersionResponse: {
            version?: string;
            commit?: string;
            date?: string;
        };
        NetworksResponse: {
            evm?: string[];
            svm?: string[];
        };
        ErrorResponse: {
            error: string;
            code: string;
            message?: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized - Invalid or missing authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEvmTransfers: {
        parameters: {
            query?: {
                /** @description Network ID (e.g., mainnet, base, arbitrum-one) */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /**
                 * @description Filter by transaction hash (supports batching with commas)
                 * @example 0x96b1b180d22dae2b18a783ebdd5ae33f6867f3572f87c69a135c6c0a15a63c8e
                 */
                transaction_id?: string;
                /**
                 * @description Filter by token contract address (supports batching with commas)
                 * @example 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
                 */
                contract?: string;
                /** @description Filter by sender address (supports batching with commas) */
                from_address?: string;
                /**
                 * @description Filter by recipient address (supports batching with commas)
                 * @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
                 */
                to_address?: string;
                /** @description Filter by start timestamp (ISO 8601 or Unix timestamp) */
                start_time?: string;
                /** @description Filter by end timestamp (ISO 8601 or Unix timestamp) */
                end_time?: string;
                /** @description Filter by start block number */
                start_block?: number;
                /** @description Filter by end block number */
                end_block?: number;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of results per page */
                limit?: number;
                /** @description Sort order (ASC or DESC by timestamp) */
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransfersResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmSwaps: {
        parameters: {
            query?: {
                /** @description Network ID (e.g., mainnet, base, arbitrum-one) */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /**
                 * @description Filter by transaction hash (supports batching with commas)
                 * @example 0xf6374799c227c9db38ff5ac1d5bebe8b607a1de1238cd861ebd1053ec07305ca
                 */
                transaction_id?: string;
                /**
                 * @description Filter by pool address (supports batching with commas)
                 * @example 0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640
                 */
                pool?: string;
                /** @description Filter by caller address (supports batching with commas) */
                caller?: string;
                /** @description Filter by sender address (supports batching with commas) */
                sender?: string;
                /** @description Filter by recipient address (supports batching with commas) */
                recipient?: string;
                /** @description Filter by DEX protocol */
                protocol?: "uniswap_v2" | "uniswap_v3";
                /** @description Filter by start timestamp (ISO 8601 or Unix timestamp) */
                start_time?: string;
                /** @description Filter by end timestamp (ISO 8601 or Unix timestamp) */
                end_time?: string;
                /** @description Filter by start block number */
                start_block?: number;
                /** @description Filter by end block number */
                end_block?: number;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of results per page */
                limit?: number;
                /** @description Sort order (ASC or DESC by timestamp) */
                order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmTokens: {
        parameters: {
            query?: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /** @description Token contract address (supports batching with commas) */
                contract?: string;
                /** @description Token symbol (e.g., ETH, USDC) */
                symbol?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmBalances: {
        parameters: {
            query: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /**
                 * @description Wallet address to get balances for
                 * @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
                 */
                owner: string;
                /** @description Filter by token contract address */
                contract?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmHolders: {
        parameters: {
            query: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /** @description Token contract address */
                contract: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldersResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmPrices: {
        parameters: {
            query?: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /** @description Token contract address (supports batching with commas) */
                contract?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmOhlc: {
        parameters: {
            query: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /** @description Token contract address */
                contract: string;
                /** @description Time interval for candlesticks */
                interval?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | "1w";
                start_time?: string;
                end_time?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvmPools: {
        parameters: {
            query?: {
                /** @description Network ID */
                network?: "mainnet" | "base" | "arbitrum-one" | "bsc" | "polygon" | "optimism" | "avalanche" | "unichain";
                /** @description Pool address (supports batching with commas) */
                pool?: string;
                /** @description Token0 contract address */
                token0?: string;
                /** @description Token1 contract address */
                token1?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version Info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    getNetworks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Networks List */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworksResponse"];
                };
            };
        };
    };
}
